name: Create Python Application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8

    - name: Check code formatting with Black
      run: |
        black --check .
  
  build-ubuntu:
    runs-on: ubuntu-latest
    needs: checks

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Create executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed app.py

    - name: Upload binaries to release
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/app
        asset_name: GerImagesFromOBJ_APP
        tag: ${{ github.ref }}_ubuntu
        overwrite: true
        body: "Get Images from OBJ application from main branch"

  build-windows:
    runs-on: windows-latest
    needs: checks

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Create executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed app.py

    - name: Upload binaries to release
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/app.exe
        asset_name: GerImagesFromOBJ_APP.exe
        tag: ${{ github.ref }}_windows
        overwrite: true
        body: "Get Images from OBJ application from main branch"

  build-macos:
    runs-on: macos-latest
    needs: checks

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Create executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed app.py

    - name: Upload binaries to release
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/app
        asset_name: GerImagesFromOBJ_APP
        tag: ${{ github.ref }}_macos
        overwrite: true
        body: "Get Images from OBJ application from main branch"